#ifdef _KERNEL_ERR_H_
#define _KERNEL_ERR_H_

/* This file provides MACRO for error field encoding. The error field is 
 * a 16 bit value with MSByte for Error type and LSByte for Error value
 */

/* Error type */
#define TIMER_ERR       1 << 8
#define TASK_ERR        TIMER_ERR << 1
#define SEMAPHORE_ERR   TASK_ERR << 1
#define EVENT_ERR       SEMAPHORE_ERR << 1
#define EXCEPTION_ERR   EVENT_ERR << 1

/* Error value */
#define ERR_EXCP_INVALID_IRQ    EXCEPTION_ERR + 1
#define ERR_EXCP_INVALID_BHALF  ERR_EXCP_INVALID_IRQ + 1
#define ERR_EXCP_BHALF_CONFLICT ERR_EXCP_INVALID_BHALF + 1
#define ERR_EXCP_BHALF_ACTIVATE ERR_EXCP_BHALF_CONFLICT + 1

#define ERR_TIM_INVALID_HANDLER TIMER_ERR + 1
#define ERR_TIM_INVALID_TVALUE  ERR_TIM_INVALID_HANDLER + 1
#define ERR_TIM_EXCEED_TIMERS   ERR_TIM_INVALID_TVALUE + 1
#define ERR_TIM_INVALID_FLAGS   ERR_TIM_EXCEED_TIMERS + 1
#define ERR_TIM_INVALID_PARAM   ERR_TIM_INVALID_FLAGS + 1
#define ERR_TIM_INVALID_ID      ERR_TIM_INVALID_PARAM + 1

#define ERR_TASK_USTACK_ALLOC   TASK_ERR + 1
#define ERR_TASK_PRIORITY       ERR_TASK_USTACK_ALLOC + 1
#define ERR_TASK_TCB_NULL       ERR_TASK_PRIORITY + 1
#define ERR_TASK_RLINK_FAIL     ERR_TASK_TCB_NULL + 1
#define ERR_TASK_INVALID_PARAM  ERR_TASK_RLINK_FAIL + 1
#define ERR_TASK_WLINK_FAIL     ERR_TASK_INVALID_PARAM + 1
#define ERR_TASK_TO_READY       ERR_TASK_WLINK_FAIL + 1

#endif /* _KERNEL_ERR_H_*/
